# Generated by Django 4.0.1 on 2022-01-19 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartWaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('wait_time', models.PositiveSmallIntegerField(verbose_name='한 테이블 당 식사시간')),
                ('table_number', models.PositiveSmallIntegerField(verbose_name='테이블 수')),
                ('phone_number', models.CharField(default='', max_length=11, verbose_name='전화번호')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='대기번호')),
                ('mode', models.BooleanField(default=False)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startWaitings', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startWaitings', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('number', models.PositiveSmallIntegerField(verbose_name='대기번호')),
                ('time', models.PositiveSmallIntegerField(verbose_name='대기시간')),
                ('people_number', models.PositiveSmallIntegerField(verbose_name='인원수')),
                ('startWaiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='waiting.startwaiting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
