# Generated by Django 4.0.1 on 2022-01-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0002_alter_waiting_store_startwaiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiting.startwaiting'),
        ),
    ]
