# Generated by Django 4.0.1 on 2022-01-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0003_alter_waiting_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiting',
            old_name='store',
            new_name='startWaiting',
        ),
    ]
