# Generated by Django 4.0.1 on 2022-01-13 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waiting', '0004_rename_store_waiting_startwaiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
