# Generated by Django 4.0.1 on 2022-01-14 00:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0006_rename_user_startwaiting_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='startwaiting',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='startwaiting',
            name='table_number',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='테이블 수'),
        ),
        migrations.AddField(
            model_name='startwaiting',
            name='wait_time',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='한 테이블 당 식사시간'),
        ),
    ]
