# Generated by Django 4.0.1 on 2022-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0007_startwaiting_phone_number_startwaiting_table_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startwaiting',
            name='phone_number',
            field=models.CharField(default='', max_length=11, verbose_name='전화번호'),
        ),
    ]
