# Generated by Django 4.0.1 on 2022-01-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0008_alter_startwaiting_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiting',
            name='number',
        ),
        migrations.AddField(
            model_name='waiting',
            name='people_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='인원수'),
            preserve_default=False,
        ),
    ]
