# Generated by Django 4.0.1 on 2022-01-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0009_remove_waiting_number_waiting_people_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='대기번호'),
            preserve_default=False,
        ),
    ]
