# Generated by Django 4.0.1 on 2022-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0013_alter_startwaiting_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startwaiting',
            name='mode',
            field=models.BooleanField(default=False),
        ),
    ]
