# Generated by Django 4.0.1 on 2022-01-18 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0009_alter_image_store'),
        ('waiting', '0014_startwaiting_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startwaiting',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startWaitings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startwaiting',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startWaitings', to='stores.store'),
        ),
    ]
