# Generated by Django 4.0.1 on 2022-01-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0015_alter_startwaiting_master_alter_startwaiting_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='startWaiting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='waiting.startwaiting'),
        ),
    ]
