# Generated by Django 4.0.1 on 2022-01-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='stores/qrcode/%Y/%m/%d'),
        ),
    ]
