# Generated by Django 4.0.1 on 2022-01-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='stores/qrcode/'),
        ),
    ]
