# Generated by Django 4.0.1 on 2022-01-13 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_amenity_foodtype_storetype_tag_store_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='food_type',
        ),
        migrations.AddField(
            model_name='store',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='stores.foodtype'),
        ),
        migrations.RemoveField(
            model_name='store',
            name='tags',
        ),
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.CharField(default='', max_length=200, verbose_name='태그'),
        ),
    ]
