# Generated by Django 4.0.1 on 2022-01-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_store_food_type_store_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.store'),
        ),
    ]
